version: '3'
services:

  bot:
    build:
      dockerfile: Dockerfile-bot
    depends_on:
      - postgres
    volumes: ['.:/friendly-levels-bot']  # remove if live reload not needed
    tty: true

  postgres:
    build:
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    tty: true
