FROM python:3.11

WORKDIR /friendly-levels-bot

COPY Pipfile ./

RUN pip install pipenv

RUN pip install discord.py
RUN pip install python-dotenv
RUN pip install loguru
RUN pip install psycopg

COPY . .

CMD ["python", "main.py"]
