version: '3'
services:

  bot:
    build:
      dockerfile: Dockerfile-bot
    depends_on:
      - postgres

  postgres:
    build:
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"