FROM python:3.11
#FROM python:alpine3.18

WORKDIR /friendly-levels-bot

COPY requirements.txt ./
RUN pip install -r requirements.txt

# copy is used when volumnes are not mounted. right now it's overwritten
COPY . .

CMD ["jurigged", "-v", "main.py"]
